// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: driver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

type Machine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID       string            `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	State      int32             `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	DriverID   int32             `protobuf:"varint,3,opt,name=DriverID,proto3" json:"DriverID,omitempty"`
	Tags       []string          `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CustomInfo map[string]string `protobuf:"bytes,5,rep,name=CustomInfo,proto3" json:"CustomInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Machine) Reset() {
	*x = Machine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_driver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

func (x *Machine) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Machine) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Machine) GetDriverID() int32 {
	if x != nil {
		return x.DriverID
	}
	return 0
}

func (x *Machine) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Machine) GetCustomInfo() map[string]string {
	if x != nil {
		return x.CustomInfo
	}
	return nil
}

var File_driver_proto protoreflect.FileDescriptor

var file_driver_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xdc, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x38, 0x0a,
	0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3d, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xb3, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x08, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x0d, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x4d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x22,
	0x0a, 0x0e, 0x4d, 0x52, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x45, 0x78, 0x69, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_driver_proto_rawDescOnce sync.Once
	file_driver_proto_rawDescData = file_driver_proto_rawDesc
)

func file_driver_proto_rawDescGZIP() []byte {
	file_driver_proto_rawDescOnce.Do(func() {
		file_driver_proto_rawDescData = protoimpl.X.CompressGZIP(file_driver_proto_rawDescData)
	})
	return file_driver_proto_rawDescData
}

var file_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_driver_proto_goTypes = []interface{}{
	(*Empty)(nil),   // 0: Empty
	(*Machine)(nil), // 1: Machine
	nil,             // 2: Machine.CustomInfoEntry
}
var file_driver_proto_depIdxs = []int32{
	2, // 0: Machine.CustomInfo:type_name -> Machine.CustomInfoEntry
	0, // 1: MachineDriver.InitMachine:input_type -> Empty
	0, // 2: MachineDriver.CreateExec:input_type -> Empty
	0, // 3: MachineDriver.InstallMRobot:input_type -> Empty
	0, // 4: MachineDriver.MRoHealthCheck:input_type -> Empty
	0, // 5: MachineDriver.Exit:input_type -> Empty
	1, // 6: MachineDriver.InitMachine:output_type -> Machine
	0, // 7: MachineDriver.CreateExec:output_type -> Empty
	0, // 8: MachineDriver.InstallMRobot:output_type -> Empty
	0, // 9: MachineDriver.MRoHealthCheck:output_type -> Empty
	0, // 10: MachineDriver.Exit:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_driver_proto_init() }
func file_driver_proto_init() {
	if File_driver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_driver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_driver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Machine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_driver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_proto_goTypes,
		DependencyIndexes: file_driver_proto_depIdxs,
		MessageInfos:      file_driver_proto_msgTypes,
	}.Build()
	File_driver_proto = out.File
	file_driver_proto_rawDesc = nil
	file_driver_proto_goTypes = nil
	file_driver_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MachineDriverClient is the client API for MachineDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineDriverClient interface {
	// InitMachine create a machine to store
	InitMachine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machine, error)
	// CreateExec driver to execute really create action for a machine
	CreateExec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// InstallMRobot install machine robot in this new machine
	InstallMRobot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// MRoHealthCheck check machine robot install successfully or not
	MRoHealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Exit driver exit
	Exit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type machineDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineDriverClient(cc grpc.ClientConnInterface) MachineDriverClient {
	return &machineDriverClient{cc}
}

func (c *machineDriverClient) InitMachine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machine, error) {
	out := new(Machine)
	err := c.cc.Invoke(ctx, "/MachineDriver/InitMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineDriverClient) CreateExec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/MachineDriver/CreateExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineDriverClient) InstallMRobot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/MachineDriver/InstallMRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineDriverClient) MRoHealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/MachineDriver/MRoHealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineDriverClient) Exit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/MachineDriver/Exit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineDriverServer is the server API for MachineDriver service.
type MachineDriverServer interface {
	// InitMachine create a machine to store
	InitMachine(context.Context, *Empty) (*Machine, error)
	// CreateExec driver to execute really create action for a machine
	CreateExec(context.Context, *Empty) (*Empty, error)
	// InstallMRobot install machine robot in this new machine
	InstallMRobot(context.Context, *Empty) (*Empty, error)
	// MRoHealthCheck check machine robot install successfully or not
	MRoHealthCheck(context.Context, *Empty) (*Empty, error)
	// Exit driver exit
	Exit(context.Context, *Empty) (*Empty, error)
}

// UnimplementedMachineDriverServer can be embedded to have forward compatible implementations.
type UnimplementedMachineDriverServer struct {
}

func (*UnimplementedMachineDriverServer) InitMachine(context.Context, *Empty) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMachine not implemented")
}
func (*UnimplementedMachineDriverServer) CreateExec(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExec not implemented")
}
func (*UnimplementedMachineDriverServer) InstallMRobot(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallMRobot not implemented")
}
func (*UnimplementedMachineDriverServer) MRoHealthCheck(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MRoHealthCheck not implemented")
}
func (*UnimplementedMachineDriverServer) Exit(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}

func RegisterMachineDriverServer(s *grpc.Server, srv MachineDriverServer) {
	s.RegisterService(&_MachineDriver_serviceDesc, srv)
}

func _MachineDriver_InitMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineDriverServer).InitMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MachineDriver/InitMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineDriverServer).InitMachine(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineDriver_CreateExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineDriverServer).CreateExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MachineDriver/CreateExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineDriverServer).CreateExec(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineDriver_InstallMRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineDriverServer).InstallMRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MachineDriver/InstallMRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineDriverServer).InstallMRobot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineDriver_MRoHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineDriverServer).MRoHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MachineDriver/MRoHealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineDriverServer).MRoHealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineDriver_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineDriverServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MachineDriver/Exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineDriverServer).Exit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MachineDriver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MachineDriver",
	HandlerType: (*MachineDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitMachine",
			Handler:    _MachineDriver_InitMachine_Handler,
		},
		{
			MethodName: "CreateExec",
			Handler:    _MachineDriver_CreateExec_Handler,
		},
		{
			MethodName: "InstallMRobot",
			Handler:    _MachineDriver_InstallMRobot_Handler,
		},
		{
			MethodName: "MRoHealthCheck",
			Handler:    _MachineDriver_MRoHealthCheck_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _MachineDriver_Exit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
