// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: worker0.proto

package worker0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App_MainProcess_PType int32

const (
	App_MainProcess_Binary App_MainProcess_PType = 0
	App_MainProcess_Image  App_MainProcess_PType = 1
)

// Enum value maps for App_MainProcess_PType.
var (
	App_MainProcess_PType_name = map[int32]string{
		0: "Binary",
		1: "Image",
	}
	App_MainProcess_PType_value = map[string]int32{
		"Binary": 0,
		"Image":  1,
	}
)

func (x App_MainProcess_PType) Enum() *App_MainProcess_PType {
	p := new(App_MainProcess_PType)
	*p = x
	return p
}

func (x App_MainProcess_PType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App_MainProcess_PType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker0_proto_enumTypes[0].Descriptor()
}

func (App_MainProcess_PType) Type() protoreflect.EnumType {
	return &file_worker0_proto_enumTypes[0]
}

func (x App_MainProcess_PType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App_MainProcess_PType.Descriptor instead.
func (App_MainProcess_PType) EnumDescriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 0, 0}
}

type App_Network_PortInf_Protocol int32

const (
	App_Network_PortInf_TCP App_Network_PortInf_Protocol = 0
	App_Network_PortInf_UDP App_Network_PortInf_Protocol = 1
)

// Enum value maps for App_Network_PortInf_Protocol.
var (
	App_Network_PortInf_Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	App_Network_PortInf_Protocol_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x App_Network_PortInf_Protocol) Enum() *App_Network_PortInf_Protocol {
	p := new(App_Network_PortInf_Protocol)
	*p = x
	return p
}

func (x App_Network_PortInf_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App_Network_PortInf_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_worker0_proto_enumTypes[1].Descriptor()
}

func (App_Network_PortInf_Protocol) Type() protoreflect.EnumType {
	return &file_worker0_proto_enumTypes[1]
}

func (x App_Network_PortInf_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App_Network_PortInf_Protocol.Descriptor instead.
func (App_Network_PortInf_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 3, 0, 0}
}

type App_Network_RouteInf_Route int32

const (
	App_Network_RouteInf_IN  App_Network_RouteInf_Route = 0
	App_Network_RouteInf_OUT App_Network_RouteInf_Route = 1
)

// Enum value maps for App_Network_RouteInf_Route.
var (
	App_Network_RouteInf_Route_name = map[int32]string{
		0: "IN",
		1: "OUT",
	}
	App_Network_RouteInf_Route_value = map[string]int32{
		"IN":  0,
		"OUT": 1,
	}
)

func (x App_Network_RouteInf_Route) Enum() *App_Network_RouteInf_Route {
	p := new(App_Network_RouteInf_Route)
	*p = x
	return p
}

func (x App_Network_RouteInf_Route) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App_Network_RouteInf_Route) Descriptor() protoreflect.EnumDescriptor {
	return file_worker0_proto_enumTypes[2].Descriptor()
}

func (App_Network_RouteInf_Route) Type() protoreflect.EnumType {
	return &file_worker0_proto_enumTypes[2]
}

func (x App_Network_RouteInf_Route) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App_Network_RouteInf_Route.Descriptor instead.
func (App_Network_RouteInf_Route) EnumDescriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 3, 1, 0}
}

// supported http method
type App_Health_Basic_Method int32

const (
	App_Health_Basic_GET  App_Health_Basic_Method = 0
	App_Health_Basic_POST App_Health_Basic_Method = 1
)

// Enum value maps for App_Health_Basic_Method.
var (
	App_Health_Basic_Method_name = map[int32]string{
		0: "GET",
		1: "POST",
	}
	App_Health_Basic_Method_value = map[string]int32{
		"GET":  0,
		"POST": 1,
	}
)

func (x App_Health_Basic_Method) Enum() *App_Health_Basic_Method {
	p := new(App_Health_Basic_Method)
	*p = x
	return p
}

func (x App_Health_Basic_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App_Health_Basic_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_worker0_proto_enumTypes[3].Descriptor()
}

func (App_Health_Basic_Method) Type() protoreflect.EnumType {
	return &file_worker0_proto_enumTypes[3]
}

func (x App_Health_Basic_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App_Health_Basic_Method.Descriptor instead.
func (App_Health_Basic_Method) EnumDescriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 7, 0, 0}
}

type NewAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *NewAppReq) Reset() {
	*x = NewAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAppReq) ProtoMessage() {}

func (x *NewAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAppReq.ProtoReflect.Descriptor instead.
func (*NewAppReq) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{0}
}

func (x *NewAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewAppReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID            string             `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	MainP           *App_MainProcess   `protobuf:"bytes,2,opt,name=MainP,proto3" json:"MainP,omitempty"`
	FileMounts      []*App_FileMount   `protobuf:"bytes,3,rep,name=FileMounts,proto3" json:"FileMounts,omitempty"`
	EnvironmentVars []*App_EnvVar      `protobuf:"bytes,4,rep,name=EnvironmentVars,proto3" json:"EnvironmentVars,omitempty"`
	Networks        []*App_Network     `protobuf:"bytes,5,rep,name=Networks,proto3" json:"Networks,omitempty"`
	Workspace       *App_WorkspaceInfo `protobuf:"bytes,6,opt,name=Workspace,proto3" json:"Workspace,omitempty"`
	FilePremise     []*App_File        `protobuf:"bytes,7,rep,name=FilePremise,proto3" json:"FilePremise,omitempty"`
	LimitInfo       *App_Limit         `protobuf:"bytes,8,opt,name=LimitInfo,proto3" json:"LimitInfo,omitempty"`
	HealthInfo      *App_Health        `protobuf:"bytes,9,opt,name=HealthInfo,proto3" json:"HealthInfo,omitempty"`
	LogInfo         *App_Log           `protobuf:"bytes,10,opt,name=LogInfo,proto3" json:"LogInfo,omitempty"`
	Tags            []*App_Tag         `protobuf:"bytes,11,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *App) GetMainP() *App_MainProcess {
	if x != nil {
		return x.MainP
	}
	return nil
}

func (x *App) GetFileMounts() []*App_FileMount {
	if x != nil {
		return x.FileMounts
	}
	return nil
}

func (x *App) GetEnvironmentVars() []*App_EnvVar {
	if x != nil {
		return x.EnvironmentVars
	}
	return nil
}

func (x *App) GetNetworks() []*App_Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *App) GetWorkspace() *App_WorkspaceInfo {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *App) GetFilePremise() []*App_File {
	if x != nil {
		return x.FilePremise
	}
	return nil
}

func (x *App) GetLimitInfo() *App_Limit {
	if x != nil {
		return x.LimitInfo
	}
	return nil
}

func (x *App) GetHealthInfo() *App_Health {
	if x != nil {
		return x.HealthInfo
	}
	return nil
}

func (x *App) GetLogInfo() *App_Log {
	if x != nil {
		return x.LogInfo
	}
	return nil
}

func (x *App) GetTags() []*App_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{2}
}

type App_MainProcess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckSum string                `protobuf:"bytes,1,opt,name=CheckSum,proto3" json:"CheckSum,omitempty"`
	Name     string                `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version  string                `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Type     App_MainProcess_PType `protobuf:"varint,4,opt,name=Type,proto3,enum=worker0.App_MainProcess_PType" json:"Type,omitempty"`
	Workdir  string                `protobuf:"bytes,5,opt,name=Workdir,proto3" json:"Workdir,omitempty"`
	StartCMD []string              `protobuf:"bytes,6,rep,name=StartCMD,proto3" json:"StartCMD,omitempty"`
}

func (x *App_MainProcess) Reset() {
	*x = App_MainProcess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_MainProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_MainProcess) ProtoMessage() {}

func (x *App_MainProcess) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_MainProcess.ProtoReflect.Descriptor instead.
func (*App_MainProcess) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 0}
}

func (x *App_MainProcess) GetCheckSum() string {
	if x != nil {
		return x.CheckSum
	}
	return ""
}

func (x *App_MainProcess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App_MainProcess) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App_MainProcess) GetType() App_MainProcess_PType {
	if x != nil {
		return x.Type
	}
	return App_MainProcess_Binary
}

func (x *App_MainProcess) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *App_MainProcess) GetStartCMD() []string {
	if x != nil {
		return x.StartCMD
	}
	return nil
}

// 将文件挂载到对应的目录
// File 表示要被挂载的文件
// MountTo 表示挂载到的地方
// Volume 一般不填这个字段，除非有对应的卷存在
type App_FileMount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File    string `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	MountTo string `protobuf:"bytes,2,opt,name=MountTo,proto3" json:"MountTo,omitempty"`
	Volume  string `protobuf:"bytes,3,opt,name=Volume,proto3" json:"Volume,omitempty"`
}

func (x *App_FileMount) Reset() {
	*x = App_FileMount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_FileMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_FileMount) ProtoMessage() {}

func (x *App_FileMount) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_FileMount.ProtoReflect.Descriptor instead.
func (*App_FileMount) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 1}
}

func (x *App_FileMount) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *App_FileMount) GetMountTo() string {
	if x != nil {
		return x.MountTo
	}
	return ""
}

func (x *App_FileMount) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type App_EnvVar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *App_EnvVar) Reset() {
	*x = App_EnvVar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_EnvVar) ProtoMessage() {}

func (x *App_EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_EnvVar.ProtoReflect.Descriptor instead.
func (*App_EnvVar) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 2}
}

func (x *App_EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *App_EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type App_Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortInfo  *App_Network_PortInf    `protobuf:"bytes,1,opt,name=PortInfo,proto3" json:"PortInfo,omitempty"`
	RouteInfo []*App_Network_RouteInf `protobuf:"bytes,2,rep,name=RouteInfo,proto3" json:"RouteInfo,omitempty"`
}

func (x *App_Network) Reset() {
	*x = App_Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Network) ProtoMessage() {}

func (x *App_Network) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Network.ProtoReflect.Descriptor instead.
func (*App_Network) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 3}
}

func (x *App_Network) GetPortInfo() *App_Network_PortInf {
	if x != nil {
		return x.PortInfo
	}
	return nil
}

func (x *App_Network) GetRouteInfo() []*App_Network_RouteInf {
	if x != nil {
		return x.RouteInfo
	}
	return nil
}

type App_WorkspaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=Workspace,proto3" json:"Workspace,omitempty"`
}

func (x *App_WorkspaceInfo) Reset() {
	*x = App_WorkspaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_WorkspaceInfo) ProtoMessage() {}

func (x *App_WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*App_WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 4}
}

func (x *App_WorkspaceInfo) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type App_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	AcquireAddr string `protobuf:"bytes,2,opt,name=AcquireAddr,proto3" json:"AcquireAddr,omitempty"`
	Shell       string `protobuf:"bytes,3,opt,name=Shell,proto3" json:"Shell,omitempty"`
}

func (x *App_File) Reset() {
	*x = App_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_File) ProtoMessage() {}

func (x *App_File) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_File.ProtoReflect.Descriptor instead.
func (*App_File) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 5}
}

func (x *App_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App_File) GetAcquireAddr() string {
	if x != nil {
		return x.AcquireAddr
	}
	return ""
}

func (x *App_File) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type App_Limit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// unit 'm'
	CPU int32 `protobuf:"varint,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	// unit 'MB'
	Memory int32 `protobuf:"varint,2,opt,name=Memory,proto3" json:"Memory,omitempty"`
}

func (x *App_Limit) Reset() {
	*x = App_Limit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Limit) ProtoMessage() {}

func (x *App_Limit) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Limit.ProtoReflect.Descriptor instead.
func (*App_Limit) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 6}
}

func (x *App_Limit) GetCPU() int32 {
	if x != nil {
		return x.CPU
	}
	return 0
}

func (x *App_Limit) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type App_Health struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url to judge app living
	Liveness *App_Health_Basic `protobuf:"bytes,1,opt,name=Liveness,proto3" json:"Liveness,omitempty"`
	// url to judge app working
	Readness *App_Health_Basic `protobuf:"bytes,2,opt,name=Readness,proto3" json:"Readness,omitempty"`
}

func (x *App_Health) Reset() {
	*x = App_Health{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Health) ProtoMessage() {}

func (x *App_Health) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Health.ProtoReflect.Descriptor instead.
func (*App_Health) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 7}
}

func (x *App_Health) GetLiveness() *App_Health_Basic {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *App_Health) GetReadness() *App_Health_Basic {
	if x != nil {
		return x.Readness
	}
	return nil
}

type App_Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Real-time log file name. eg: xxx/log.log
	RealTimeFile string `protobuf:"bytes,1,opt,name=RealTimeFile,proto3" json:"RealTimeFile,omitempty"`
	// path of compress log file
	FilePath string `protobuf:"bytes,2,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
}

func (x *App_Log) Reset() {
	*x = App_Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Log) ProtoMessage() {}

func (x *App_Log) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Log.ProtoReflect.Descriptor instead.
func (*App_Log) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 8}
}

func (x *App_Log) GetRealTimeFile() string {
	if x != nil {
		return x.RealTimeFile
	}
	return ""
}

func (x *App_Log) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type App_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *App_Tag) Reset() {
	*x = App_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Tag) ProtoMessage() {}

func (x *App_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Tag.ProtoReflect.Descriptor instead.
func (*App_Tag) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 9}
}

func (x *App_Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *App_Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type App_Network_PortInf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port         int32                        `protobuf:"varint,1,opt,name=Port,proto3" json:"Port,omitempty"`
	Name         string                       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ProtocolType App_Network_PortInf_Protocol `protobuf:"varint,3,opt,name=ProtocolType,proto3,enum=worker0.App_Network_PortInf_Protocol" json:"ProtocolType,omitempty"`
}

func (x *App_Network_PortInf) Reset() {
	*x = App_Network_PortInf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Network_PortInf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Network_PortInf) ProtoMessage() {}

func (x *App_Network_PortInf) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Network_PortInf.ProtoReflect.Descriptor instead.
func (*App_Network_PortInf) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *App_Network_PortInf) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *App_Network_PortInf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App_Network_PortInf) GetProtocolType() App_Network_PortInf_Protocol {
	if x != nil {
		return x.ProtocolType
	}
	return App_Network_PortInf_TCP
}

type App_Network_RouteInf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteType App_Network_RouteInf_Route `protobuf:"varint,1,opt,name=RouteType,proto3,enum=worker0.App_Network_RouteInf_Route" json:"RouteType,omitempty"`
	Router    string                     `protobuf:"bytes,2,opt,name=Router,proto3" json:"Router,omitempty"`
}

func (x *App_Network_RouteInf) Reset() {
	*x = App_Network_RouteInf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Network_RouteInf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Network_RouteInf) ProtoMessage() {}

func (x *App_Network_RouteInf) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Network_RouteInf.ProtoReflect.Descriptor instead.
func (*App_Network_RouteInf) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 3, 1}
}

func (x *App_Network_RouteInf) GetRouteType() App_Network_RouteInf_Route {
	if x != nil {
		return x.RouteType
	}
	return App_Network_RouteInf_IN
}

func (x *App_Network_RouteInf) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

type App_Health_Basic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodType App_Health_Basic_Method `protobuf:"varint,1,opt,name=MethodType,proto3,enum=worker0.App_Health_Basic_Method" json:"MethodType,omitempty"`
	// path to request
	Path string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	// same as above
	Port int32 `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *App_Health_Basic) Reset() {
	*x = App_Health_Basic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker0_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App_Health_Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Health_Basic) ProtoMessage() {}

func (x *App_Health_Basic) ProtoReflect() protoreflect.Message {
	mi := &file_worker0_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Health_Basic.ProtoReflect.Descriptor instead.
func (*App_Health_Basic) Descriptor() ([]byte, []int) {
	return file_worker0_proto_rawDescGZIP(), []int{1, 7, 0}
}

func (x *App_Health_Basic) GetMethodType() App_Health_Basic_Method {
	if x != nil {
		return x.MethodType
	}
	return App_Health_Basic_GET
}

func (x *App_Health_Basic) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *App_Health_Basic) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_worker0_proto protoreflect.FileDescriptor

var file_worker0_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x22, 0x39, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0xda, 0x0e, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x2e, 0x0a, 0x05, 0x4d, 0x61, 0x69, 0x6e, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4d, 0x61, 0x69,
	0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x05, 0x4d, 0x61, 0x69, 0x6e, 0x50, 0x12,
	0x36, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70,
	0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x45,
	0x6e, 0x76, 0x56, 0x61, 0x72, 0x52, 0x0f, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x56, 0x61, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x08,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x6d, 0x69, 0x73,
	0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0b, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x72, 0x65, 0x6d, 0x69, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x09,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x0a, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a,
	0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x6f,
	0x67, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73,
	0x1a, 0xe1, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x50, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x64, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x57, 0x6f, 0x72, 0x6b, 0x64, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x4d, 0x44, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x4d, 0x44, 0x22, 0x1e, 0x0a, 0x05, 0x50, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x10, 0x01, 0x1a, 0x51, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x1a, 0x30, 0x0a, 0x06, 0x45, 0x6e, 0x76, 0x56, 0x61,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x9e, 0x03, 0x0a, 0x07, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x38, 0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x50, 0x6f,
	0x72, 0x74, 0x49, 0x6e, 0x66, 0x52, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3b, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x9a, 0x01, 0x0a,
	0x07, 0x50, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30,
	0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x50, 0x6f, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x0c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x01, 0x1a, 0x7f, 0x0a, 0x08, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x12, 0x41, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x09, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x22, 0x18, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55, 0x54, 0x10, 0x01, 0x1a, 0x2d, 0x0a, 0x0d, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x52, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x1a, 0x31, 0x0a,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x50, 0x55, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x1a, 0x87, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x35, 0x0a, 0x08, 0x4c,
	0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x6e, 0x65,
	0x73, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41,
	0x70, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x08, 0x52, 0x65, 0x61, 0x64, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x8e, 0x01, 0x0a, 0x05, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x12, 0x40, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x1b, 0x0a,
	0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x1a, 0x45, 0x0a, 0x03, 0x4c, 0x6f,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x1a, 0x2d, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xf1, 0x04, 0x0a, 0x07, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x30, 0x12, 0x2c, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x41, 0x70, 0x70, 0x12,
	0x12, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70,
	0x70, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x70, 0x70, 0x12,
	0x0c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x1a, 0x0e, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x29, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x12, 0x0c, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x1a, 0x0e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x44, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x79, 0x41, 0x70, 0x70, 0x12, 0x0c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x1a, 0x0e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x54, 0x61, 0x67, 0x45,
	0x78, 0x12, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e,
	0x54, 0x61, 0x67, 0x1a, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70,
	0x70, 0x2e, 0x54, 0x61, 0x67, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x12, 0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30,
	0x2e, 0x41, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x16,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x05, 0x45, 0x6e, 0x76, 0x45,
	0x78, 0x12, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e,
	0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x1a, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30,
	0x2e, 0x41, 0x70, 0x70, 0x2e, 0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x09, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x78, 0x12, 0x14, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x1a, 0x14, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x72, 0x65, 0x6d, 0x69, 0x73, 0x65, 0x45, 0x78, 0x12, 0x11, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x11, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x07, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x45, 0x78, 0x12, 0x12, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x1a, 0x12, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x45, 0x78, 0x12, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x1a, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x00, 0x12, 0x2d,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x45, 0x78, 0x12, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x6f, 0x67, 0x1a, 0x10, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x4c, 0x6f, 0x67, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_worker0_proto_rawDescOnce sync.Once
	file_worker0_proto_rawDescData = file_worker0_proto_rawDesc
)

func file_worker0_proto_rawDescGZIP() []byte {
	file_worker0_proto_rawDescOnce.Do(func() {
		file_worker0_proto_rawDescData = protoimpl.X.CompressGZIP(file_worker0_proto_rawDescData)
	})
	return file_worker0_proto_rawDescData
}

var file_worker0_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_worker0_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_worker0_proto_goTypes = []interface{}{
	(App_MainProcess_PType)(0),        // 0: worker0.App.MainProcess.PType
	(App_Network_PortInf_Protocol)(0), // 1: worker0.App.Network.PortInf.Protocol
	(App_Network_RouteInf_Route)(0),   // 2: worker0.App.Network.RouteInf.Route
	(App_Health_Basic_Method)(0),      // 3: worker0.App.Health.Basic.Method
	(*NewAppReq)(nil),                 // 4: worker0.NewAppReq
	(*App)(nil),                       // 5: worker0.App
	(*Empty)(nil),                     // 6: worker0.Empty
	(*App_MainProcess)(nil),           // 7: worker0.App.MainProcess
	(*App_FileMount)(nil),             // 8: worker0.App.FileMount
	(*App_EnvVar)(nil),                // 9: worker0.App.EnvVar
	(*App_Network)(nil),               // 10: worker0.App.Network
	(*App_WorkspaceInfo)(nil),         // 11: worker0.App.WorkspaceInfo
	(*App_File)(nil),                  // 12: worker0.App.File
	(*App_Limit)(nil),                 // 13: worker0.App.Limit
	(*App_Health)(nil),                // 14: worker0.App.Health
	(*App_Log)(nil),                   // 15: worker0.App.Log
	(*App_Tag)(nil),                   // 16: worker0.App.Tag
	(*App_Network_PortInf)(nil),       // 17: worker0.App.Network.PortInf
	(*App_Network_RouteInf)(nil),      // 18: worker0.App.Network.RouteInf
	(*App_Health_Basic)(nil),          // 19: worker0.App.Health.Basic
}
var file_worker0_proto_depIdxs = []int32{
	7,  // 0: worker0.App.MainP:type_name -> worker0.App.MainProcess
	8,  // 1: worker0.App.FileMounts:type_name -> worker0.App.FileMount
	9,  // 2: worker0.App.EnvironmentVars:type_name -> worker0.App.EnvVar
	10, // 3: worker0.App.Networks:type_name -> worker0.App.Network
	11, // 4: worker0.App.Workspace:type_name -> worker0.App.WorkspaceInfo
	12, // 5: worker0.App.FilePremise:type_name -> worker0.App.File
	13, // 6: worker0.App.LimitInfo:type_name -> worker0.App.Limit
	14, // 7: worker0.App.HealthInfo:type_name -> worker0.App.Health
	15, // 8: worker0.App.LogInfo:type_name -> worker0.App.Log
	16, // 9: worker0.App.Tags:type_name -> worker0.App.Tag
	0,  // 10: worker0.App.MainProcess.Type:type_name -> worker0.App.MainProcess.PType
	17, // 11: worker0.App.Network.PortInfo:type_name -> worker0.App.Network.PortInf
	18, // 12: worker0.App.Network.RouteInfo:type_name -> worker0.App.Network.RouteInf
	19, // 13: worker0.App.Health.Liveness:type_name -> worker0.App.Health.Basic
	19, // 14: worker0.App.Health.Readness:type_name -> worker0.App.Health.Basic
	1,  // 15: worker0.App.Network.PortInf.ProtocolType:type_name -> worker0.App.Network.PortInf.Protocol
	2,  // 16: worker0.App.Network.RouteInf.RouteType:type_name -> worker0.App.Network.RouteInf.Route
	3,  // 17: worker0.App.Health.Basic.MethodType:type_name -> worker0.App.Health.Basic.Method
	4,  // 18: worker0.Worker0.NewApp:input_type -> worker0.NewAppReq
	5,  // 19: worker0.Worker0.StartApp:input_type -> worker0.App
	5,  // 20: worker0.Worker0.StopApp:input_type -> worker0.App
	5,  // 21: worker0.Worker0.DestroyApp:input_type -> worker0.App
	16, // 22: worker0.Worker0.TagEx:input_type -> worker0.App.Tag
	8,  // 23: worker0.Worker0.FileMountEx:input_type -> worker0.App.FileMount
	9,  // 24: worker0.Worker0.EnvEx:input_type -> worker0.App.EnvVar
	10, // 25: worker0.Worker0.NetworkEx:input_type -> worker0.App.Network
	12, // 26: worker0.Worker0.FilePremiseEx:input_type -> worker0.App.File
	13, // 27: worker0.Worker0.LimitEx:input_type -> worker0.App.Limit
	14, // 28: worker0.Worker0.HealthEx:input_type -> worker0.App.Health
	15, // 29: worker0.Worker0.LogEx:input_type -> worker0.App.Log
	5,  // 30: worker0.Worker0.NewApp:output_type -> worker0.App
	6,  // 31: worker0.Worker0.StartApp:output_type -> worker0.Empty
	6,  // 32: worker0.Worker0.StopApp:output_type -> worker0.Empty
	6,  // 33: worker0.Worker0.DestroyApp:output_type -> worker0.Empty
	16, // 34: worker0.Worker0.TagEx:output_type -> worker0.App.Tag
	8,  // 35: worker0.Worker0.FileMountEx:output_type -> worker0.App.FileMount
	9,  // 36: worker0.Worker0.EnvEx:output_type -> worker0.App.EnvVar
	10, // 37: worker0.Worker0.NetworkEx:output_type -> worker0.App.Network
	12, // 38: worker0.Worker0.FilePremiseEx:output_type -> worker0.App.File
	13, // 39: worker0.Worker0.LimitEx:output_type -> worker0.App.Limit
	14, // 40: worker0.Worker0.HealthEx:output_type -> worker0.App.Health
	15, // 41: worker0.Worker0.LogEx:output_type -> worker0.App.Log
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_worker0_proto_init() }
func file_worker0_proto_init() {
	if File_worker0_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_worker0_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_MainProcess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_FileMount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_EnvVar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_WorkspaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Limit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Health); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Network_PortInf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Network_RouteInf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker0_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App_Health_Basic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_worker0_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker0_proto_goTypes,
		DependencyIndexes: file_worker0_proto_depIdxs,
		EnumInfos:         file_worker0_proto_enumTypes,
		MessageInfos:      file_worker0_proto_msgTypes,
	}.Build()
	File_worker0_proto = out.File
	file_worker0_proto_rawDesc = nil
	file_worker0_proto_goTypes = nil
	file_worker0_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Worker0Client is the client API for Worker0 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Worker0Client interface {
	NewApp(ctx context.Context, in *NewAppReq, opts ...grpc.CallOption) (*App, error)
	StartApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error)
	StopApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error)
	DestroyApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error)
	// --- construct App ---
	TagEx(ctx context.Context, in *App_Tag, opts ...grpc.CallOption) (*App_Tag, error)
	FileMountEx(ctx context.Context, in *App_FileMount, opts ...grpc.CallOption) (*App_FileMount, error)
	EnvEx(ctx context.Context, in *App_EnvVar, opts ...grpc.CallOption) (*App_EnvVar, error)
	NetworkEx(ctx context.Context, in *App_Network, opts ...grpc.CallOption) (*App_Network, error)
	FilePremiseEx(ctx context.Context, in *App_File, opts ...grpc.CallOption) (*App_File, error)
	LimitEx(ctx context.Context, in *App_Limit, opts ...grpc.CallOption) (*App_Limit, error)
	HealthEx(ctx context.Context, in *App_Health, opts ...grpc.CallOption) (*App_Health, error)
	LogEx(ctx context.Context, in *App_Log, opts ...grpc.CallOption) (*App_Log, error)
}

type worker0Client struct {
	cc grpc.ClientConnInterface
}

func NewWorker0Client(cc grpc.ClientConnInterface) Worker0Client {
	return &worker0Client{cc}
}

func (c *worker0Client) NewApp(ctx context.Context, in *NewAppReq, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/NewApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) StartApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/StartApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) StopApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/StopApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) DestroyApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/DestroyApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) TagEx(ctx context.Context, in *App_Tag, opts ...grpc.CallOption) (*App_Tag, error) {
	out := new(App_Tag)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/TagEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) FileMountEx(ctx context.Context, in *App_FileMount, opts ...grpc.CallOption) (*App_FileMount, error) {
	out := new(App_FileMount)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/FileMountEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) EnvEx(ctx context.Context, in *App_EnvVar, opts ...grpc.CallOption) (*App_EnvVar, error) {
	out := new(App_EnvVar)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/EnvEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) NetworkEx(ctx context.Context, in *App_Network, opts ...grpc.CallOption) (*App_Network, error) {
	out := new(App_Network)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/NetworkEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) FilePremiseEx(ctx context.Context, in *App_File, opts ...grpc.CallOption) (*App_File, error) {
	out := new(App_File)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/FilePremiseEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) LimitEx(ctx context.Context, in *App_Limit, opts ...grpc.CallOption) (*App_Limit, error) {
	out := new(App_Limit)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/LimitEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) HealthEx(ctx context.Context, in *App_Health, opts ...grpc.CallOption) (*App_Health, error) {
	out := new(App_Health)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/HealthEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker0Client) LogEx(ctx context.Context, in *App_Log, opts ...grpc.CallOption) (*App_Log, error) {
	out := new(App_Log)
	err := c.cc.Invoke(ctx, "/worker0.Worker0/LogEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Worker0Server is the server API for Worker0 service.
type Worker0Server interface {
	NewApp(context.Context, *NewAppReq) (*App, error)
	StartApp(context.Context, *App) (*Empty, error)
	StopApp(context.Context, *App) (*Empty, error)
	DestroyApp(context.Context, *App) (*Empty, error)
	// --- construct App ---
	TagEx(context.Context, *App_Tag) (*App_Tag, error)
	FileMountEx(context.Context, *App_FileMount) (*App_FileMount, error)
	EnvEx(context.Context, *App_EnvVar) (*App_EnvVar, error)
	NetworkEx(context.Context, *App_Network) (*App_Network, error)
	FilePremiseEx(context.Context, *App_File) (*App_File, error)
	LimitEx(context.Context, *App_Limit) (*App_Limit, error)
	HealthEx(context.Context, *App_Health) (*App_Health, error)
	LogEx(context.Context, *App_Log) (*App_Log, error)
}

// UnimplementedWorker0Server can be embedded to have forward compatible implementations.
type UnimplementedWorker0Server struct {
}

func (*UnimplementedWorker0Server) NewApp(context.Context, *NewAppReq) (*App, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewApp not implemented")
}
func (*UnimplementedWorker0Server) StartApp(context.Context, *App) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartApp not implemented")
}
func (*UnimplementedWorker0Server) StopApp(context.Context, *App) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopApp not implemented")
}
func (*UnimplementedWorker0Server) DestroyApp(context.Context, *App) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyApp not implemented")
}
func (*UnimplementedWorker0Server) TagEx(context.Context, *App_Tag) (*App_Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagEx not implemented")
}
func (*UnimplementedWorker0Server) FileMountEx(context.Context, *App_FileMount) (*App_FileMount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileMountEx not implemented")
}
func (*UnimplementedWorker0Server) EnvEx(context.Context, *App_EnvVar) (*App_EnvVar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnvEx not implemented")
}
func (*UnimplementedWorker0Server) NetworkEx(context.Context, *App_Network) (*App_Network, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkEx not implemented")
}
func (*UnimplementedWorker0Server) FilePremiseEx(context.Context, *App_File) (*App_File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilePremiseEx not implemented")
}
func (*UnimplementedWorker0Server) LimitEx(context.Context, *App_Limit) (*App_Limit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LimitEx not implemented")
}
func (*UnimplementedWorker0Server) HealthEx(context.Context, *App_Health) (*App_Health, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthEx not implemented")
}
func (*UnimplementedWorker0Server) LogEx(context.Context, *App_Log) (*App_Log, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEx not implemented")
}

func RegisterWorker0Server(s *grpc.Server, srv Worker0Server) {
	s.RegisterService(&_Worker0_serviceDesc, srv)
}

func _Worker0_NewApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).NewApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/NewApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).NewApp(ctx, req.(*NewAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_StartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).StartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/StartApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).StartApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_StopApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).StopApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/StopApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).StopApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_DestroyApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).DestroyApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/DestroyApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).DestroyApp(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_TagEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_Tag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).TagEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/TagEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).TagEx(ctx, req.(*App_Tag))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_FileMountEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_FileMount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).FileMountEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/FileMountEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).FileMountEx(ctx, req.(*App_FileMount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_EnvEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_EnvVar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).EnvEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/EnvEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).EnvEx(ctx, req.(*App_EnvVar))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_NetworkEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).NetworkEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/NetworkEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).NetworkEx(ctx, req.(*App_Network))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_FilePremiseEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).FilePremiseEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/FilePremiseEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).FilePremiseEx(ctx, req.(*App_File))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_LimitEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_Limit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).LimitEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/LimitEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).LimitEx(ctx, req.(*App_Limit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_HealthEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_Health)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).HealthEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/HealthEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).HealthEx(ctx, req.(*App_Health))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker0_LogEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App_Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker0Server).LogEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker0.Worker0/LogEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker0Server).LogEx(ctx, req.(*App_Log))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker0_serviceDesc = grpc.ServiceDesc{
	ServiceName: "worker0.Worker0",
	HandlerType: (*Worker0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewApp",
			Handler:    _Worker0_NewApp_Handler,
		},
		{
			MethodName: "StartApp",
			Handler:    _Worker0_StartApp_Handler,
		},
		{
			MethodName: "StopApp",
			Handler:    _Worker0_StopApp_Handler,
		},
		{
			MethodName: "DestroyApp",
			Handler:    _Worker0_DestroyApp_Handler,
		},
		{
			MethodName: "TagEx",
			Handler:    _Worker0_TagEx_Handler,
		},
		{
			MethodName: "FileMountEx",
			Handler:    _Worker0_FileMountEx_Handler,
		},
		{
			MethodName: "EnvEx",
			Handler:    _Worker0_EnvEx_Handler,
		},
		{
			MethodName: "NetworkEx",
			Handler:    _Worker0_NetworkEx_Handler,
		},
		{
			MethodName: "FilePremiseEx",
			Handler:    _Worker0_FilePremiseEx_Handler,
		},
		{
			MethodName: "LimitEx",
			Handler:    _Worker0_LimitEx_Handler,
		},
		{
			MethodName: "HealthEx",
			Handler:    _Worker0_HealthEx_Handler,
		},
		{
			MethodName: "LogEx",
			Handler:    _Worker0_LogEx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker0.proto",
}
